name: Spotly CI/CD Pipeline

on:
  push:
    branches:
      - testing
      - staging
  pull_request:
    branches:
      - testing

jobs:
  # CI (para testing y staging)
  lint:
    name: Run ESLint & Prettier
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/testing' || github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier Check
        run: npm run format -- --check

  type-check:
    name: TypeScript Type Checking
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/testing' || github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run TypeScript Type Checking
        run: npm run type-check

  # CD (solo staging)
  deploy:
    name: Deploy to Vercel (Staging)
    needs: type-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' && success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
